### ISSUE TITLE
Stopped working in Thunderbird 57 beta

### ISSUE THREAD

**Issue by ElhemEnohpi** [trlkly/dorando-keyconfig#18]
As I mentioned in issue #16 , Keyconfig has stopped working for me in Thunderbird beta channel, starting with 57 beta in early November. It continues to fail in 58 beta.

I can still open the Keyconfig window, but the list of key assignments is blank. I now get the old default Thunderbird key assignments.

**Comment by jikamens** [comment]
I believe this is fixed with 280e54bad784741ebcada089b0b0aa1fd9eabdf0.

Can you try [this version of the add-on](https://gofile.me/2J75a/nn2DLRTM3) and tell me if it works for you?

**Comment by jikamens** [comment]
Sorry, please use this link instead for the add-on version to try: https://gofile.me/2J75a/txexyvFNQ

**Comment by ElhemEnohpi** [comment]
It seems to work ok for TB 57, thanks! But in 58, although the Keyconfig window is no longer blank, it just has the default assignments. My custom keys are missing, standard keys I had remapped are back to default, and all the single-key shortcuts I disabled are re-enabled again.

**Comment by jikamens** [comment]
>It seems to work ok for TB 57, but in 58, although the Keyconfig window is no longer blank, it just has the default assignments. My custom keys are missing, standard keys I had remapped are back to default, and all the single-key shortcuts I disabled are re-enabled again.

Unfortunately, this isn't going to be fixed until the fix for [bug 1414398](https://bugzilla.mozilla.org/show_bug.cgi?id=1414398) lands in the source tree and is released in a nightly and beta builds.

**Comment by ElhemEnohpi** [comment]
Ok, thanks. Sounds like it's likely to be fixed in the next TB 58 beta release.

**Comment by jikamens** [comment]
Version 2017.1 which I just uploaded to AMO should work with all TB builds up to and including today's nightly build. If not, please reopen. You can wait until you get the update automatically once it's approved, or download it from [here](https://addons.mozilla.org/firefox/downloads/file/812397/dorando_keyconfig-2017.1-an+fx+sm+tb.xpi?src=devhub) and install it manually.

**Comment by ElhemEnohpi** [comment]
Seems to be working, thanks very much!!
