### ISSUE TITLE
[request] Remove "experimental" tag

### ISSUE THREAD

**Issue by ElhemEnohpi** [trlkly/dorando-keyconfig#19]
I'm not sure what's involved, but it would be nice if Keyconfig was no longer "experimental". It's been stable for me for years, and the "experimental" tag I think makes it more difficult to find in the addons search, and makes people less confident about installing it.

**Comment by jikamens** [comment]
I would have no objection to removing the experimental flag from the add-on, but it's @trlkly's call, since he's the primary maintainer.

**Comment by trlkly** [comment]
I included the tag to avoid having to go through a more rigorous testing
procedure that might require me to heavily rewrite the addon.

At this point, I'm not sure AMO is even doing reviews for legacy
extensions, so I'm not sure
if it is even possible. I would hope they will continue to allow updates
until Firefox 61 is released, but I do not know even that.

My plan had always been to turn things over to you by this time anyways, so
feel free to look into it. I'll just try to work out how to switch things
over. (I would like to keep my name on there, if only because I put so much
time and effort into supporting it.)

**Comment by jikamens** [comment]
The Thunderbird team is in the process of creating a separate web site from addons.mozilla.org where Thunderbird add-ons will be hosted and distributed moving forward. I think once that new web site is up and running, we should release a new, non-experimental version of the add-on there without Firefox support specified in install.rdf, and leave the last version on AMO to be one with legacy Firefox support (up to Firefox 57).

If anyone wants to take a stab at rewriting the add-on's functionality as a WebExtension for the current Firefox, that would be great, but I don't think either you or I is prepared to volunteered to do that, and I believe that the work required to do so would essentially mean rewriting the majority of the add-on's code from scratch, so I think it would essentially be a different add-on.

Certainly, Firefox and Thunderbird add-ons sharing the same code base looks like it's a thing of the past, at least for now.

**Comment by trlkly** [comment]
From what I've looked into, writing it with WebExtensions isn't a
possibility. The underlying concept just has to change into something that
wouldn't really be recognizable as the same extension. Barring an actual
API that lets you change existing keyboard shortcuts, it's really more just
putting together a bunch of functions and then letting you set keyboard
shortcuts to those by injecting code into the content, which then pass a
message back to the actual extension.

You're honestly better off using something like AutoHotkey if you're
wanting to change the shortcuts in Firefox.

**Comment by ElhemEnohpi** [comment]
Updates to legacy addons are still being reviewed. According to [this Mozilla blog post](https://blog.mozilla.org/addons/2016/08/19/a-simpler-add-on-review-process/), since last year there's no difference between the "experimental" review process and the full one:
> Starting on August 22nd, there will be one review level for all add-ons listed on AMO. Developers who want to reduce the visibility of their add-ons will be able to set an “experimental” add-on flag in the AMO developer tools. This flag won’t have any effect on how an add-on is reviewed or updated.

So as far as I can tell, when you submit the next Keyconfig update, i.e. for Thunderbird 57+ compatibility, it will go through the full review, and you should remove the "experimental" tag. I'd  encourage that it be done this way, rather than wait for a new separate Thunderbird addon repository; and also that a single version compatible with both Thunderbird and legacy Firefox is maintained if possible. It's not only because we don't know how long a new repository will take, but also because with Firefox 52 ESR, and with the Waterfox project which is maintaining a fork of Firefox 56 with security updates indefinitely, I think there are potentially still several years of useful life left for Keyconfig in the browser for many people.

I've posted a [note in the Mozilla forum](https://discourse.mozilla.org/t/updating-an-experimental-addon-keyconfig-might-it-get-deleted/23346) to confirm the above, and ask whether there's any danger that initiating a full review might get it kicked out of AMO altogether.

As far as a Web Extension version, there's already [shortkeys](https://github.com/mikecrittenden/shortkeys). It does as well as can be expected I think, given the major limitations of web extensions. So I think there's no real need for a Keyconfig WE.

**Comment by jikamens** [comment]
I've disabled the experimental flag. We'll see what happens.

(Having said that, AMO just changed to make it much harder to find Thunderbird add-ons. So there's going to be a bumpy transition until the new site for Thunderbird add-ons is up and running and everybody's migrated over to it.)

**Comment by ElhemEnohpi** [comment]
One reviewer on the Mozilla forum was of the (not terribly authoritative) opinion, that if it's not approved for some reason with the new stricter review, it won't affect the old version, which can just stay there as "experimental" for Firefox. I'll keep my fingers crossed, and thanks again...

**Comment by ElhemEnohpi** [comment]
The new version passed the audition and just showed up on AMO, no longer "experimental"! Now it can be found with search in FF 56 or earlier, for example searching on "keyboard shortcuts" or "keyconfig" now works.

For some reason it doesn't show up from Thunderbird's "search all addons" box under Extensions, though it does if you click on "see all 1200 results", or if you go to the "Get Add-ons" pane.

Great work, thanks!

**Comment by jikamens** [comment]
>For some reason it doesn't show up from Thunderbird's "search all addons" box under Extensions, though it does if you click on "see all 1200 results", or if you go to the "Get Add-ons" pane.

I think add-ons you already have installed don't show up in those search results?

**Comment by ElhemEnohpi** [comment]
You're right, that explains it. Perfect...

**Comment by grahamperrin** [comment]
:+1: 

Dorando keyconfig is first and foremost when _keyconfig_ is sought from within the Add-ons page of Thunderbird 60. 

```text
$ thunderbird --version
 Thunderbird 60.0
$ pkg info thunderbird | grep Version
Version        : 60.0_1
$ date ; uname -v
Sat 28 Jul 2018 07:31:46 BST
FreeBSD 12.0-CURRENT #7 r336136: Tue Jul 10 03:01:24 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
$ 
```

Incidentally: 

- [Legacy Extensions Database · Issue #303 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/303)
