### ISSUE TITLE
Pale Moon?

### ISSUE THREAD

**Issue by Lootyhoof** [trlkly/dorando-keyconfig#24]
Hi there, is it possible to add support for [Pale Moon](https://www.palemoon.org) in your `install.rdf`? This add-on already works fine in Pale Moon, and just needs the following adding:

````
    <targetApplication><rdf:Description>
      <id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</id> <!--Pale Moon-->
      <minVersion>25.0</minVersion>
      <maxVersion>27.*</maxVersion>
    </rdf:Description></targetApplication>
````
With this, it would also be eligible for hosting on the [Pale Moon Add-ons Site](https://addons.palemoon.org), if interested. Here, there are no plans to remove XUL add-ons, as Pale Moon itself only supports these add-ons and not WebExtensions. If interested please let me know and I can help get you setup; there is also further information available [here](https://developer.palemoon.org/Add-ons:Site/Submit).

Thanks!

**Comment by jikamens** [comment]
I'd rather not have to track Pale Moon versions. Can we just put '*' in the maxVersion field and assume that someone who's using Pale Moon will contact us if it stops working and needs to be fixed in a newer version?

**Comment by Lootyhoof** [comment]
No, you should not use `*` as `maxVersion`,  as this implies compatibility that might not be there, and also proves ambiguity as to what versions *are* supported.

Milestone versions of Pale Moon are very infrequent (for example, 27.0.0 was released 2016-11-22), and prove to be substantially large updates. If a theoretical v28 came out and broke something, users wouldn't know that version isn't immediately supported. If the `maxVersion` was `27.*`, though, they would know that work hasn't gone into v28 yet and (potentially) submit a bug report to let someone know. These would still install in v28, as `maxVersion` isn't strict in Pale Moon, therefore you could update that at a later time if you wanted, and it wouldn't affect the user in any way. If there was any particular need to update that, too, we could always get in touch, or users could report it if there's somehow an issue surrounding that.

**Comment by jikamens** [comment]
>No, you should not use `*` as `maxVersion`, as this implies compatibility that might not be there, and also proves ambiguity as to what versions are supported.

\*sigh\*

I currently maintain 11 add-ons, and I've been maintaining add-ons for almost six years. I know what putting `*` in `maxVersion` does. Please don't lecture me.

I'm not asking for permission, I'm asking if Pale Moon has done anything to prevent `*` from working in the `maxVersion` field. This add-on is pretty much static and rarely requires new releases, and I don't want to have to waste my time several times per year putting out a new release just to change the Pale Moon compatibility number.

I am willing to add the Pale Moon stanza to the add-on's install.rdf if `*` in `maxVersion` will work. Otherwise, not so much, for a browser with so little market share that it [doesn't even register in the data](https://netmarketshare.com/browser-market-share.aspx).

**Comment by Lootyhoof** [comment]
Yes, it is possible to use them. Add-ons with `*` in `maxVersion` are not permitted on our add-ons site, though, and with [support for updating from AMO going away soon](https://forum.palemoon.org/viewtopic.php?f=44&t=17829) as a result of [Mozilla removing XUL add-ons from AMO soon](https://blog.mozilla.org/addons/2017/10/03/legacy-add-on-support-on-firefox-esr/#comment-224377), the only other way of reliably providing updates for Pale Moon users is to self-host updates using `updateURL` in `install.rdf`. 

I'm sorry if what I said came off as a lecture, but besides that, it's likely you wouldn't need to update that number at all within a year or more. As mentioned, Pale Moon doesn't update its milestone version as much as other applications do, as it's only for particularly large updates. I also wouldn't say it's crucial to keep it updated ASAP either, there's no major concern.

**Comment by jikamens** [comment]
Is there any plan for the Pale Moon add-ons site to support automatic updates for add-ons hosted there?

Is there a system in place for Pale Moon add-on maintainers to upload their add-ons to the site, or is it a manual process managed by volunteers at Pale Moon?

Are there reviewers checking Pale Moon add-ons before they are put on the site, like the reviewers at AMO?

**Comment by Lootyhoof** [comment]
>Is there any plan for the Pale Moon add-ons site to support automatic updates for add-ons hosted there?

This is already in place. Add-ons hosted there are automatically sent to users when an update is released.

>Is there a system in place for Pale Moon add-on maintainers to upload their add-ons to the site, or is it a manual process managed by volunteers at Pale Moon?

Currently there is an FTP system in place, where you upload your files and edit a small amount of metadata and the update file is sent to users. We do plan to get a self-service web-based system setup in the future, though.

>Are there reviewers checking Pale Moon add-ons before they are put on the site, like the reviewers at AMO?

In the initial release, we check for any issues before setting up the add-on on the site. With subsequent releases, no, as you can upload directly to the system and have that be sent to users. We would of course intervene if there were issues reported by users (for example, if an add-on completely broke the browser somehow). It's possible this could change with the planned web-based system, however I can't confirm anything currently.

**Comment by jikamens** [comment]
OK, I pushed a new version to AMO with Pale Moon compatibility. What's next? Is there a page you can point me at which the steps I need to follow?

**Comment by Lootyhoof** [comment]
Great! Full information on what's needed next can be seen [here](https://developer.palemoon.org/Add-ons:Site/Submit), under the `Hosting your Add-on` section. If you could send me an email (address in my GitHub profile) with the following information (most of this can be pulled from the existing AMO entry if desired) and I can get this setup for you:

>You should submit a request to the Add-ons Team with the following information:
>
>- A 64x64 alpha transparent icon in the PNG format (we can use the generic green puzzle piece if you simply don't have one)
>- A slug version of your extensions name to be used for internal identification and URL generation (For example, a name of 'My Add-on' would become 'my-add-on' -- it is meant to be unique). Only lower case letters (a-z), numbers (0-9) and dashes (-) are permitted here.
>- Category to be listed on (only one per add-on is allowed at this time; additionally, themes do not use categories): see the full list [here](http://addons.palemoon.org/extensions/).
>- Long Description for the actual add-on's page (if applicable otherwise Short Description will be used)
>- The Initial XPI for review and initial setup
>- A user name for FTP access so that you can update your add-on later. We will assign you a lengthy (25 chars or so) random alpha-numeric password which will be promptly forgotten by us.
>
>Optionally, you could also provide the following, to be shown on the add-on listing:
>
>- Author Name (as you want it on the page) - this uses the 'creator' tag in install.rdf if available, else this is used.
>- Short Description for the category listing (~200 character limit)
>- License - both OSI-approved licenses and custom licenses are allowed here. If a license is not provided, a default copyright notice is shown instead.
>- Code repository URL (e.g. GitHub repo)
>- Homepage URL - this uses the 'homepageURL' tag in install.rdf if available, else this is used.
>- Support URL
>- Support email address
>- Preview image - note that currently only one preview image can be shown for each listing
>
>Please note that the add-on name is read from your add-on's install.rdf, so please take this into consideration when submitting.

**Comment by Lootyhoof** [comment]
For those curious, this is now live here: https://addons.palemoon.org/addon/keyconfig/

Thanks again for the support!
