### ISSUE TITLE
Changes Ctrl-Enter to Send Later

### ISSUE THREAD

**Issue by JeremyStein** [trlkly/dorando-keyconfig#25]
When I activate the Dorando add-on with Thunderbird, I lose my Ctrl-Enter behavior.  It reverts to Send Later.  How can I keep Ctrl-Enter as Send Now?

**Comment by jikamens** [comment]
Hi, I'm not sure what you mean by "reverts." The default behavior of Thunderbird for Ctrl-Enter is Send Now, not Send Later, so "reverting" would presumably be back to that default behavior not some non-default behavior.
Note that both the Send button and Ctrl-Enter switch from Send Now to Send Later automatically when Thunderbird thinks the network is disconnected, i.e., when it switches into offline automatically. Is it possible that's what's happening here?
If not, then off the top of my head I'm not sure why installing Keyconfig would cause the behavior of Ctrl-Enter to change. This is not the behavior I see when I test this in a new, clean Thunderbird profile -- install Keyconfig, restart, compose message, type Ctrl-Enter, message sends.
Do you have other addons installed? Have you tweaked key bindings in the past? Do you see a binding for Ctrl-Enter when you open Tools | Keyconfig... in the compose window? This is what I see:

![keyconfig_019](https://user-images.githubusercontent.com/1598067/41468891-678e87e0-7079-11e8-9716-19621949faa9.png)

Do you see something different?

**Comment by JeremyStein** [comment]
When add-on is disabled, Ctrl-Enter works correctly.  When disabled, it works incorrectly.

I didn't realize the Keyconfig options were context sensitive.  I hadn't been able to figure out where Send Now and Send Later were defined!  Thank you.

This is what I see:

![keyconfig](https://user-images.githubusercontent.com/474154/41469071-f0905eea-70a3-11e8-8bba-7861b45d0804.png)

I do not remember modifying any keymappings.  Maybe it's possible I messed with something long ago before installing this add-on?

Changing the mappings here fixes my problem.  Thank you.
