### ISSUE TITLE
Duplicate listings for some shortcuts

### ISSUE THREAD

**Issue by grahamperrin** [trlkly/dorando-keyconfig#26]
With one of my Waterfox profiles, for example:

![2018-07-28 07 02 51 keyconfig](https://user-images.githubusercontent.com/192271/43353932-f3cb0bf2-9239-11e8-9a4e-0d1bde84eae2.png)

Please, is the symptom recognisable? 

An extension conflict, maybe? (I could use [Extension Conflict Troubleshooter](https://addons.mozilla.org/addon/extension-conflict-troubleshoo/), but with the number of extensions that I have enabled, it'll be time-consuming.)

I just discovered #4 so I know to no longer bother disabling developer shortcuts. 

Dev tools aside, I have a _vague_ recollection of seeing duplication with other shortcuts in the past. Unfortunately no screenshot handy. 

```text
$ pkg info waterfox | grep Version
Version        : 56.2.2
$ date ; uname -v
Sat 28 Jul 2018 07:44:08 BST
FreeBSD 12.0-CURRENT #7 r336136: Tue Jul 10 03:01:24 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
$ 
```

**Comment by jikquantopian** [comment]
Don't know what causes this. Reluctant to spend a lot of time investigating to find out, given that it's harmless.

**Comment by jikamens** [comment]
Don't know what causes this. Reluctant to spend time investigating it given that it's harmless.

**Comment by grahamperrin** [comment]
OK
