### ISSUE TITLE
REQUEST:  Make keyconfig dialog expandable

### ISSUE THREAD

**Issue by VLM1** [trlkly/dorando-keyconfig#5]
In the old keyconfig, the user could expand the dialog, at least vertically. This made it possible, say, to sort by shortcut and then to scan (with the eyes). One could take in much more information this way than in the fixed-size window presently available.

Thank you!

**Comment by trlkly** [comment]
I am not having any trouble with resizing the dialog. I go to the bottom corner and can drag to resize. I've tried opening the dialog via the ALT menu, the Add-ons Manager, and by pressing Ctrl-Shift-F12.

Can you give me a full bug report? You know, OS and version, Firefox version, any addons you think might be relevant, and the exact steps to reproduce?

I can't make any promises, but I can at least look.

**Comment by VLM1** [comment]
We had a power outage earlier today, and that seemed to mess some things
up. After a few system reboots, most of them ... including resizing the
keyconfig dialog ... seem to working fine.

I apologize for bothering you for what turned out to be nothing, and I
appreciate your timely response.

Kind regards,
Elchanan

On Fri, August 19, 2016 7:01 pm, trlkly wrote:
I am not having any trouble with resizing the dialog. I go to the bottom
corner and can drag to resize. I've tried opening the dialog via the ALT
menu, the Add-ons Manager, and by pressing Ctrl-Shift-F12.

Can you give me a full bug report? You know, OS and version, Firefox
version, any addons you think might be relevant, and the exact steps to
reproduce?

I can't make any promises, but I can at least look.

**Comment by trlkly** [comment]
Glad to know. Closing this.
