### ISSUE TITLE
Cannot install from Thunderbird

### ISSUE THREAD

**Issue by AdamPS** [trlkly/dorando-keyconfig#6]
Thanks it's great on my Firefox.

Similar to #2 I am having trouble installing on Thunderbird.  I can see the add-on exists at https://addons.mozilla.org/en-GB/thunderbird/addon/dorando-keyconfig/.  So I could download it and install from file, but I think I might then lose automatic updates.

Within Thunderbird, I enter the Add-ons manager and go to the search tab, and type "Dorando keyconfig" (also tried other variants), but I can't get a matching result.  I don't have a "Show All ___ addons" box as you mentioned in the other issue.

I already have the original Dorando KeyConfig installed - might that be the problem?  I am nervous to uninstall that first in case I lose my key settings.  Can you tell me if it would be safe to do that please?

Thunderbird 45.2.0
Windows 7

Many thanks

**Comment by trlkly** [comment]
You scrolled all the way down the search results and still don't see it? I
mean, this isn't an issue with the addon, but with Thunderbird. I don't
know what to do if they won't let you see preliminarily reviewed addons.

I will say that it's unlikely there will be any real updates to this addon
at this point, unless something breaks and there's an easy fix. And things
are much less likely to break in Thunderbird since it does full updates so
rarely.

**Comment by AdamPS** [comment]
Thanks for the reply.  You are right - it is "preliminarily reviewed" 
that causes the problem.  I just tried a couple of others (printing 
tools and totalquickfilter) and it's the same thing.  I agree, we don't 
need updates to the add-on code.  It's more a matter of documentation 
and procedures.

This is a generic problem with "preliminarily reviewed".  Anyway I have 
found two ways:

1) Within Thunderbird (and exactly the same for Firefox)

  * Search for add-ons with a fairly short string.  I used "key". You
    must make sure that there are more results than will fit on one
    page.  However it's best not to get too many hundreds of results.
  * Then it /is/ possible to click "see all ### results".
  * However these are split onto multiple pages, and it can take a while
    to find the right one.

2) From the web.  Navigate to 
https://addons.mozilla.org/en-GB/thunderbird/addon/dorando-keyconfig/.

  * In Firefox, can simply click install.
  * In Thunderbird, you have to download it to disk, then go to
    Thunderbird and click  instead.  It looks like the add-on might
    still receive updates this way, but I can't be sure.

*Next steps*

 1. The whole business seems pretty silly to me.  I will raise it with
    Mozilla. Perhaps they might at least make a page documenting the
    above that you can then link to from your add-on page.
 2. What would it take to get your add-on "fully reviewed"?  Can I help?

Thanks,
Adam

**Comment by trlkly** [comment]
Closing this bug as a problem with Thunderbird and the addons.mozilla.org website.
